<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Corporate BrandingPrimary ColorHEXSecon_50cc0c</name>
   <tag></tag>
   <elementGuidId>6059d212-0f0f-4412-9903-7f3c9377c566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-card-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fd28352-cae2-4228-bebe-7a73e106035e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-card-container</value>
      <webElementGuid>5224e5ca-3072-4e83-a30c-3faf139897dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate BrandingPrimary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2Client LogoBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 50px X 50pxClient BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 182px X 50pxLogin BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 340px X 65pxSocial Media Images * Required Reset to Default  Preview  Publish </value>
      <webElementGuid>8500a565-3429-44de-82c4-9f09146d1852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]</value>
      <webElementGuid>99d482e7-7ac6-4aba-b8d1-d7dc596d4c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>12a98707-19f5-461e-a325-0ead56446c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::div[5]</value>
      <webElementGuid>98bda862-a318-4f8b-98c6-46d94bd0c9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifications'])[1]/following::div[5]</value>
      <webElementGuid>e8cfae9e-5c5e-442f-b388-609f582ecfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>10bb1b5e-1771-414c-8b0f-d8094c755665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Corporate BrandingPrimary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2Client LogoBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 50px X 50pxClient BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 182px X 50pxLogin BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 340px X 65pxSocial Media Images * Required Reset to Default  Preview  Publish ' or . = 'Corporate BrandingPrimary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2Client LogoBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 50px X 50pxClient BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 182px X 50pxLogin BannerBrowseNo file selectedAccepts jpg, .png, .gif, .svg up to 1MB. Recommended dimensions: 340px X 65pxSocial Media Images * Required Reset to Default  Preview  Publish ')]</value>
      <webElementGuid>5973cc44-a471-4921-8397-12dcd7cdb9f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
